apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kai-ba
  namespace: 'ygo-card-time'
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '0'
    run.googleapis.com/urls: '["https://kai-ba-415813429517.asia-northeast1.run.app"]'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Custom
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - name: kai-ba
          image: a9293340/kai-ba:latest
          ports:
            - name: http1
              containerPort: 3000
          env:
            # 基本環境設定
            - name: NODE_ENV
              value: production
            - name: LOG_LEVEL
              value: info

            # 快取設定
            - name: ENABLE_CACHE
              value: 'true'
            - name: ENABLE_REDIS_CACHE
              value: 'true'
            - name: ENABLE_MEMORY_CACHE
              value: 'true'
            - name: KAI_BA_CACHE_PREFIX
              value: 'KAI_BA'

            # Redis 設定
            - name: ENABLE_REDIS
              value: 'true'

            # Rate Limit 設定
            - name: RATE_LIMIT_ENABLED
              value: 'true'
            - name: RATE_LIMIT_TIME_WINDOW_SECONDS
              value: '60'
            - name: RATE_LIMIT_MAX_COEF
              value: '10'

            # Response Validation
            - name: RESPONSE_VALIDATION
              value: 'true'

            # MongoDB 環境變數 (從 Secret Manager)
            - name: ADMIN
              valueFrom:
                secretKeyRef:
                  name: MONGO_ADMIN
                  key: latest
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: MONGO_PASSWORD
                  key: latest
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: MONGO_DB
                  key: latest

            # Redis 環境變數 (從 Secret Manager)
            - name: REDIS_CONNECTION_STRING_READ
              valueFrom:
                secretKeyRef:
                  name: REDIS_CONNECTION_STRING_READ
                  key: latest
            - name: REDIS_CONNECTION_STRING_WRITE
              valueFrom:
                secretKeyRef:
                  name: REDIS_CONNECTION_STRING_WRITE
                  key: latest

            # JWT & Cookie Secrets (從 Secret Manager)
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: JWT_SECRET
                  key: latest
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: COOKIE_SECRET
                  key: latest

          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              path: /_hc
              port: 3000

          startupProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 6
            httpGet:
              path: /_hc
              port: 3000

  traffic:
    - percent: 100
      latestRevision: true
      tag: 'latest'
