/* eslint-disable */

//! auto generated from json schema
export const usefulDatabaseCardsDataSchema = {
  $id: 'https://card.time.com/schema/useful/database/cards-data',
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'database cards-data schema',
  description: 'YGO Card Time database cards-data schema',
  type: 'object',
  unevaluatedProperties: false,
  required: [
    '_id',
    'name',
    'id',
    'type',
    'attribute',
    'rarity',
    'product_information_type',
  ],
  properties: {
    _id: {
      $ref: 'https://card.time.com/schema/useful/value-object/meta#/$defs/_id',
    },
    name: {
      title: '名稱',
      description: '卡片名稱',
      $ref: 'https://card.time.com/schema/useful/value-object/meta#/$defs/name',
    },
    atk: {
      title: '攻擊力',
      description: '卡片攻擊力',
      $ref: 'https://card.time.com/schema/useful/value-object/meta#/$defs/atkDef',
    },
    def: {
      title: '守備力',
      description: '卡片守備力',
      $ref: 'https://card.time.com/schema/useful/value-object/meta#/$defs/atkDef',
    },
    price_info: {
      title: '露天價格',
      description: '露天價格資訊，by稀有度',
      type: 'array',
      items: {
        $ref: 'https://card.time.com/schema/useful/value-object/meta#/$defs/price_object',
      },
    },
    price_yuyu: {
      title: '悠悠亭價格',
      description: '悠悠亭價格資訊，by稀有度',
      type: 'array',
      items: {
        $ref: 'https://card.time.com/schema/useful/value-object/meta#/$defs/price_object',
      },
    },
    id: {
      title: '號碼',
      description: '卡片號碼',
      type: 'string',
      pattern: '^[A-Z0-9]{2,4}-[A-Z0-9]{2,4}$',
    },
    type: {
      title: '種類',
      description: '卡片種類',
      type: 'string',
      enum: [
        '通常怪獸',
        '效果怪獸',
        '擺動怪獸',
        '連結怪獸',
        '二重怪獸',
        '協調怪獸',
        '同步怪獸',
        '超量怪獸',
        '融合怪獸',
        '儀式怪獸',
        '靈魂怪獸',
        '聯合怪獸',
        '卡通怪獸',
        '反轉怪獸',
        '特殊召喚',
        '通常魔法',
        '速攻魔法',
        '裝備魔法',
        '永續魔法',
        '場地魔法',
        '儀式魔法',
        '通常陷阱',
        '永續陷阱',
        '反擊陷阱',
      ],
    },
    star: {
      title: '星數',
      description: '怪獸星數',
      type: 'string',
      enum: [
        '等級0',
        '等級1',
        '等級2',
        '等級3',
        '等級4',
        '等級5',
        '等級6',
        '等級7',
        '等級8',
        '等級9',
        '等級10',
        '等級11',
        '等級12',
        '階級0',
        '階級1',
        '階級2',
        '階級3',
        '階級4',
        '階級5',
        '階級6',
        '階級7',
        '階級8',
        '階級9',
        '階級10',
        '階級11',
        '階級12',
        '階級13',
        'LINK-1',
        'LINK-2',
        'LINK-3',
        'LINK-4',
        'LINK-5',
        'LINK-6',
        'LINK-7',
        'LINK-8',
      ],
    },
    attribute: {
      title: '屬性',
      description: '卡片屬性',
      type: 'string',
      enum: ['闇', '光', '炎', '水', '地', '風', '神', '魔', '罠'],
    },
    rarity: {
      title: '稀有度',
      description: '卡片稀有度',
      type: 'array',
      items: {
        type: 'string',
        enum: [
          '普卡',
          '隱普',
          '普鑽',
          '銀字',
          '亮面',
          '金亮',
          '半鑽',
          '斜鑽',
          '紅字半鑽',
          '雷射',
          '黃金',
          '凸版浮雕',
          '雕鑽',
          '白鑽',
          '紅鑽',
          '金鑽',
          '銀鑽',
          '藍鑽',
          'KC紋',
          '古文鑽',
          '決鬥傳說-金亮',
          '決鬥傳說-半鑽',
          '決鬥傳說-金鑽',
          '決鬥傳說-綠鑽',
          '全鑽',
          '亮面全鑽',
          '金亮全鑽',
          '半鑽全鑽',
          '異圖-普卡',
          '異圖-普鑽',
          '異圖-亮面',
          '異圖-亮面全鑽',
          '異圖-金亮',
          '異圖-金亮全鑽',
          '異圖-半鑽',
          '異圖-半鑽全鑽',
          '異圖-雕鑽',
          '異圖-黃金',
          '異圖-白鑽',
          '異圖-金鑽',
          '金普',
          '銀亮',
          '紅亮',
          '藍亮',
          '普卡放射鑽',
          '普卡粉鑽',
          '亮面粉鑽',
          '金亮粉鑽',
          '普卡彩鑽',
          '亮面彩鑽',
          '金亮彩鑽',
          '斜鑽彩鑽',
          '半鑽彩鑽',
          '雷射彩鑽',
          '普卡點鑽',
          '銀字點鑽',
          '亮面點鑽',
          '金亮點鑽',
          '半鑽點鑽',
          '隱普點鑽',
          '普卡碎鑽',
          '銀字碎鑽',
          '亮面碎鑽',
          '金亮碎鑽',
          '半鑽碎鑽',
          '隱普碎鑽',
          '普卡方鑽',
          '銀字方鑽',
          '亮面方鑽',
          '金亮方鑽',
          '半鑽方鑽',
          '隱普方鑽',
        ],
      },
      maxItems: 10,
      uniqueItems: true,
    },
    race: {
      title: '種族',
      description: '怪獸種族',
      type: 'string',
      enum: [
        '不死族',
        '超能族',
        '龍族',
        '惡魔族',
        '炎族',
        '幻龍族',
        '海龍族',
        '岩石族',
        '機械族',
        '魚族',
        '恐龍族',
        '鳥獸族',
        '昆虫族',
        '獸戰士族',
        '獸族',
        '植物族',
        '水族',
        '戰士族',
        '天使族',
        '魔法使族',
        '雷族',
        '爬蟲類族',
        '幻神獸族',
        '創造神族',
        '電子界族',
        '幻想魔族',
      ],
    },
    product_information_type: {
      title: '卡包',
      description: '補充包代號',
      type: 'string',
      pattern: '^[A-Z0-9]{2,4}$',
    },
    number: {
      title: '密碼',
      description: '卡片密碼',
      type: 'string',
      pattern: '^[0-9]{8}$',
    },
    effect: {
      title: '效果',
      description: '卡片效果欄位',
      type: 'string',
      maxLength: 800,
    },
  },
} as const;
