export enum DataAccessEnum {
  ADMIN = 'admin',
  BACKEND_TOKEN = 'backend_token',
  BANNER = 'banner',
  BATTLE_PAPER = 'battle_paper',
  CALENDAR = 'calendar',
  CARDS = 'cards',
  DECKS = 'decks',
  FORBIDDEN_CARD_LIST = 'forbidden_card_list',
  FRONTEND_TOKEN = 'frontend_token',
  JURISPRUDENCE = 'jurisprudence',
  META_DECK = 'meta_deck',
  PERMISSION = 'permission',
  PRODUCT_INFORMATION = 'product_information',
  PRODUCT_INFORMATION_TYPE = 'product_information_type',
  RULES = 'rules',
  SERIES_STORY = 'series_story',
  TAG = 'tag',
  USEFUL_CARD_INTRODUCTION = 'useful_card_introduction',
  PRICE_ARCHIVE = 'price_archive',
}
